apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: bookinfo
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9080
  type: LoadBalancer
  selector:
    app: productpage